name=HIRO
version=1.0.0
author=Joseph Casebeer, Takamori Robot
maintainer=Takamori Robot <outreach@takamorirobot.com>
sentence=Allows raspberry pi pico to control H.I.R.O. Model TR-01-A.
paragraph=This library allows ease of use for end users defining and controlling a H.I.R.O. model TR-01-A Robotics Platform using Raspberry pi pico.
includes= HIRO.h, HIRO_Motion.h, HIRO_Functions.h 
category=Other
url=https://www.takamorirobot.com
architectures=rp2040

